#include "FrameProcessorPlugin.h"
#include <cstring>
#include <stdexcept>
#if defined(__APPLE__)
#include <CoreVideo/CoreVideo.h>
#endif
#include "../clahe/CLAHEEngine.h"
#include "../inference/EmbeddingAverager.h"
#include "../inference/TFLiteInterpreterManager.h"
namespace offlineface::frameprocessor {
FrameProcessorPlugin::FrameProcessorPlugin(std::shared_ptr<PixelBufferPool> pool, std::shared_ptr<offlineface::clahe::CLAHEEngine> claheEngine, std::shared_ptr<offlineface::inference::TFLiteInterpreterManager> interpreterManager, std::shared_ptr<offlineface::inference::EmbeddingAverager> embeddingAverager) : pool_(std::move(pool)), claheEngine_(std::move(claheEngine)), interpreterManager_(std::move(interpreterManager)), embeddingAverager_(std::move(embeddingAverager)) { if (!pool_ || !claheEngine_ || !interpreterManager_ || !embeddingAverager_) throw std::invalid_argument("FrameProcessorPlugin dependencies must not be null"); }
FrameProcessorPlugin::~FrameProcessorPlugin() { FrameBuffer* pending = mailbox_.exchange(nullptr, std::memory_order_acq_rel); if (pending != nullptr) pool_->Release(pending); }
bool FrameProcessorPlugin::EnqueueGrayFrame(const uint8_t* source, uint32_t width, uint32_t height, uint32_t stride, uint64_t timestampNs) { if (source == nullptr || width == 0U || height == 0U || stride < width) return false; if (isProcessing_.load(std::memory_order_acquire)) return false; return SubmitFrameCopy(source, width, height, stride, timestampNs, PixelFormat::kGray8); }
#if defined(__APPLE__)
bool FrameProcessorPlugin::EnqueueAppleLumaPlane(const void* pixelBufferRef, uint32_t width, uint32_t height, uint32_t stride, uint64_t timestampNs) { if (pixelBufferRef == nullptr) return false; if (isProcessing_.load(std::memory_order_acquire)) return false; CVPixelBufferRef buffer = static_cast<CVPixelBufferRef>(const_cast<void*>(pixelBufferRef)); const CVReturn lockResult = CVPixelBufferLockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly); if (lockResult != kCVReturnSuccess) return false; const auto* yPlane = static_cast<const uint8_t*>(CVPixelBufferGetBaseAddressOfPlane(buffer, 0)); const size_t planeStride = CVPixelBufferGetBytesPerRowOfPlane(buffer, 0); const size_t planeHeight = CVPixelBufferGetHeightOfPlane(buffer, 0); const bool success = SubmitFrameCopy(yPlane, width, static_cast<uint32_t>(planeHeight), static_cast<uint32_t>(planeStride), timestampNs, PixelFormat::kNv12YPlane); CVPixelBufferUnlockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly); return success; }
#endif
ProcessedFrameResult FrameProcessorPlugin::DrainLatestResult() { std::lock_guard<std::mutex> lock(resultMutex_); return latestResult_; }
void FrameProcessorPlugin::SetInferenceCallback(std::function<void(const ProcessedFrameResult&)> callback) { callback_ = std::move(callback); }
bool FrameProcessorPlugin::SubmitFrameCopy(const uint8_t* source, uint32_t width, uint32_t height, uint32_t stride, uint64_t timestampNs, PixelFormat format) { const std::size_t requiredBytes = static_cast<std::size_t>(stride) * static_cast<std::size_t>(height); FrameBuffer* frame = pool_->Acquire(width, height, stride, format, timestampNs, requiredBytes); std::memcpy(frame->data, source, requiredBytes); std::atomic_thread_fence(std::memory_order_release); FrameBuffer* displaced = mailbox_.exchange(frame, std::memory_order_acq_rel); if (displaced != nullptr) pool_->Release(displaced); bool expected = false; if (!isProcessing_.compare_exchange_strong(expected, true, std::memory_order_acq_rel, std::memory_order_acquire)) return true; FrameBuffer* current = mailbox_.exchange(nullptr, std::memory_order_acq_rel); if (current != nullptr) ProcessCurrentFrame(current); isProcessing_.store(false, std::memory_order_release); return true; }
void FrameProcessorPlugin::ProcessCurrentFrame(FrameBuffer* frame) { std::atomic_thread_fence(std::memory_order_acquire); const uint32_t width = frame->width; const uint32_t height = frame->height; const uint32_t stride = frame->stride; std::vector<uint8_t> enhanced(static_cast<std::size_t>(width) * static_cast<std::size_t>(height), 0U); claheEngine_->Apply(frame->data, width, height, stride, enhanced.data()); std::vector<float> embedding = interpreterManager_->RunEmbedding(enhanced.data(), width, height, width); ProcessedFrameResult nextResult{}; nextResult.accepted = !embedding.empty(); nextResult.timestampNs = frame->timestampNs; nextResult.embedding = embeddingAverager_->PushEmbedding(frame->timestampNs, embedding); nextResult.sharpnessScore = ComputeSharpness(enhanced.data(), width, height, width); { std::lock_guard<std::mutex> lock(resultMutex_); latestResult_ = nextResult; } if (callback_) callback_(nextResult); pool_->Release(frame); }
float FrameProcessorPlugin::ComputeSharpness(const uint8_t* pixels, uint32_t width, uint32_t height, uint32_t stride) const { if (width < 3U || height < 3U) return 0.0f; uint64_t total = 0U; uint64_t count = 0U; for (uint32_t row = 1; row + 1U < height; ++row) { for (uint32_t column = 1; column + 1U < width; ++column) { const int center = pixels[row * stride + column]; const int laplacian = (4 * center) - pixels[row * stride + column - 1U] - pixels[row * stride + column + 1U] - pixels[(row - 1U) * stride + column] - pixels[(row + 1U) * stride + column]; total += static_cast<uint64_t>(laplacian * laplacian); ++count; } } return count == 0U ? 0.0f : static_cast<float>(total) / static_cast<float>(count); }
}
