require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OfflineFaceAuth' do
  config = use_native_modules!

  pod 'NayanNativeEngine', :path => './NayanNativeEngine.podspec'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'OfflineFaceAuthTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        build_configuration.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        build_configuration.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        build_configuration.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/../../cpp"'
      end
    end
  end
end
